services:
  - type: web
    name: mon-app-ffmpeg
    env: node # Changez selon votre runtime (python, ruby, etc.)
    plan: starter # ou le plan de votre choix
    buildCommand: |
      # Mise à jour des packages système
      apt-get update
      # Installation de FFmpeg et ses dépendances
      apt-get install -y ffmpeg
      # Vérification de l'installation
      ffmpeg -version
      # Build de votre application
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
